# Generated by Django 5.2.3

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='encrypted_face_encoding',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='encrypted_fingerprint_data',
            field=models.TextField(blank=True),
        ),
    ]
