# Generated by Django 5.2.3

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='voter_id_card',
            field=models.ImageField(blank=True, null=True, upload_to='voter_id_cards/'),
        ),
        migrations.AddField(
            model_name='voter',
            name='face_image',
            field=models.ImageField(blank=True, null=True, upload_to='voter_faces/'),
        ),
    ]
