# Generated by Django 5.2.3

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_biometric_fields'),
        ('users', '0002_add_voter_images'),
    ]

    operations = [
    ]
