# Generated by Django 5.2.3

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_merge_20250624_0200'),
    ]

    operations = [
        # This migration is just a checkpoint to ensure all biometric fields exist
        # after the merge. No actual operations are needed since they were added
        # in the previous migrations.
    ]
