# Generated by Django 5.2.3 on 2025-06-22 19:34

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blockchain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('genesis_hash', models.CharField(max_length=64)),
                ('latest_hash', models.CharField(max_length=64)),
                ('difficulty', models.IntegerField(default=4)),
                ('total_blocks', models.IntegerField(default=0)),
                ('election_id', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('data', models.JSONField()),
                ('previous_hash', models.CharField(max_length=64)),
                ('nonce', models.BigIntegerField(default=0)),
                ('hash', models.CharField(max_length=64, unique=True)),
                ('merkle_root', models.CharField(blank=True, max_length=64)),
                ('is_valid', models.BooleanField(default=True)),
                ('validator_signature', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['index'],
                'unique_together': {('index', 'hash')},
            },
        ),
        migrations.CreateModel(
            name='BlockchainAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE_BLOCK', 'Create Block'), ('MINE_BLOCK', 'Mine Block'), ('VALIDATE_CHAIN', 'Validate Chain'), ('ADD_TRANSACTION', 'Add Transaction'), ('VERIFY_VOTE', 'Verify Vote')], max_length=20)),
                ('actor_type', models.CharField(max_length=50)),
                ('actor_id', models.CharField(max_length=255)),
                ('details', models.JSONField()),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('execution_time', models.FloatField(help_text='Execution time in seconds')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blockchain.block')),
                ('blockchain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blockchain.blockchain')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='GenesisBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genesis_data', models.JSONField()),
                ('genesis_timestamp', models.DateTimeField()),
                ('creator_signature', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blockchain', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blockchain.blockchain')),
            ],
        ),
        migrations.CreateModel(
            name='VoteTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_id', models.CharField(max_length=255)),
                ('transaction_hash', models.CharField(max_length=64, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('encrypted_vote_data', models.TextField()),
                ('constituency_code', models.CharField(max_length=10)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('confirmation_count', models.IntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('geolocation', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='blockchain.block')),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('voter_id', 'block')},
            },
        ),
    ]
