# Generated by Django 5.2.3 on 2025-07-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0002_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchain',
            name='consensus_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='blockchain',
            name='last_validated_by_peers',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blockchain',
            name='network_id',
            field=models.CharField(default='main', max_length=50),
        ),
        migrations.AddField(
            model_name='blockchain',
            name='peer_count',
            field=models.IntegerField(default=0),
        ),
    ]
