# Generated by Django 5.2.3 on 2025-07-04 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0003_blockchain_consensus_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='votetransaction',
            name='digital_receipt',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
