# Generated by Django 5.2.3 on 2025-06-22 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blockchain', '0001_initial'),
        ('elections', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='constituency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.constituency'),
        ),
        migrations.AddField(
            model_name='candidatevotecount',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.candidate'),
        ),
        migrations.AddField(
            model_name='election',
            name='blockchain',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blockchain.blockchain'),
        ),
        migrations.AddField(
            model_name='election',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.adminuser'),
        ),
        migrations.AddField(
            model_name='election',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.state'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='elections.election'),
        ),
        migrations.AddField(
            model_name='electionauditlog',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.election'),
        ),
        migrations.AddField(
            model_name='electionconstituency',
            name='constituency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.constituency'),
        ),
        migrations.AddField(
            model_name='electionconstituency',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.election'),
        ),
        migrations.AddField(
            model_name='election',
            name='constituencies',
            field=models.ManyToManyField(through='elections.ElectionConstituency', to='users.constituency'),
        ),
        migrations.AddField(
            model_name='electionresult',
            name='constituency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.constituency'),
        ),
        migrations.AddField(
            model_name='electionresult',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='elections.election'),
        ),
        migrations.AddField(
            model_name='electionresult',
            name='winning_candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.candidate'),
        ),
        migrations.AddField(
            model_name='candidatevotecount',
            name='election_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_votes', to='elections.electionresult'),
        ),
        migrations.AddField(
            model_name='party',
            name='recognized_states',
            field=models.ManyToManyField(blank=True, to='users.state'),
        ),
        migrations.AddField(
            model_name='electionresult',
            name='winning_party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elections.party'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elections.party'),
        ),
        migrations.AddField(
            model_name='voterecord',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blockchain.block'),
        ),
        migrations.AddField(
            model_name='voterecord',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elections.candidate'),
        ),
        migrations.AddField(
            model_name='voterecord',
            name='constituency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.constituency'),
        ),
        migrations.AddField(
            model_name='voterecord',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.election'),
        ),
        migrations.AddField(
            model_name='votereceipt',
            name='vote_record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='elections.voterecord'),
        ),
        migrations.AddIndex(
            model_name='electionauditlog',
            index=models.Index(fields=['election', 'action'], name='elections_e_electio_2e7c61_idx'),
        ),
        migrations.AddIndex(
            model_name='electionauditlog',
            index=models.Index(fields=['timestamp'], name='elections_e_timesta_b93059_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='electionconstituency',
            unique_together={('election', 'constituency')},
        ),
        migrations.AlterUniqueTogether(
            name='candidatevotecount',
            unique_together={('election_result', 'candidate', 'round_number')},
        ),
        migrations.AlterUniqueTogether(
            name='electionresult',
            unique_together={('election', 'constituency')},
        ),
        migrations.AlterUniqueTogether(
            name='candidate',
            unique_together={('election', 'constituency', 'candidate_number'), ('nomination_id',)},
        ),
        migrations.AddIndex(
            model_name='voterecord',
            index=models.Index(fields=['election', 'constituency'], name='elections_v_electio_7e5197_idx'),
        ),
        migrations.AddIndex(
            model_name='voterecord',
            index=models.Index(fields=['voter_hash'], name='elections_v_voter_h_2fa391_idx'),
        ),
        migrations.AddIndex(
            model_name='voterecord',
            index=models.Index(fields=['transaction_hash'], name='elections_v_transac_79f1dc_idx'),
        ),
    ]
