# Generated by Django 5.2.3

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='status',
            field=models.CharField(choices=[('ANNOUNCED', 'Announced'), ('NOMINATION_OPEN', 'Nomination Open'), ('NOMINATION_CLOSED', 'Nomination Closed'), ('VOTING_OPEN', 'Voting Open'), ('VOTING_CLOSED', 'Voting Closed'), ('COUNTING', 'Counting'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ANNOUNCED', max_length=20),
        ),
        migrations.AlterField(
            model_name='party',
            name='symbol_image',
            field=models.ImageField(blank=True, upload_to='party_symbols/'),
        ),
    ]
