# Generated by Django 5.2.3 on 2025-07-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0004_auto_non_interactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='votereceipt',
            name='blockchain_position',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='votereceipt',
            name='merkle_proof',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='votereceipt',
            name='node_signature',
            field=models.TextField(blank=True),
        ),
    ]
