# Generated by Django 5.2.3 on 2025-07-04 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0005_votereceipt_blockchain_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='is_winner',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
