# Generated by Django 5.2.3 on 2025-06-22 19:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('report_period_start', models.DateTimeField()),
                ('report_period_end', models.DateTimeField()),
                ('report_data', models.JSONField()),
                ('pdf_file', models.FileField(blank=True, upload_to='reports/audit/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=False)),
                ('download_count', models.IntegerField(default=0)),
                ('digital_signature', models.TextField(blank=True)),
                ('verification_hash', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('metrics_data', models.JSONField()),
                ('charts_data', models.JSONField(blank=True, null=True)),
                ('pdf_file', models.FileField(blank=True, upload_to='reports/performance/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=False)),
                ('download_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('report_type', models.CharField(max_length=30)),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('CUSTOM', 'Custom')], max_length=20)),
                ('schedule_config', models.JSONField()),
                ('email_recipients', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('report_type', models.CharField(max_length=30)),
                ('template_config', models.JSONField()),
                ('css_styles', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VotingReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('CONSTITUENCY_RESULTS', 'Constituency Results'), ('PARTY_PERFORMANCE', 'Party Performance'), ('VOTER_TURNOUT', 'Voter Turnout'), ('ELECTION_SUMMARY', 'Election Summary'), ('CANDIDATE_WISE', 'Candidate Wise Report')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('report_data', models.JSONField()),
                ('pdf_file', models.FileField(blank=True, upload_to='reports/pdf/')),
                ('excel_file', models.FileField(blank=True, upload_to='reports/excel/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=False)),
                ('download_count', models.IntegerField(default=0)),
                ('digital_signature', models.TextField(blank=True)),
                ('verification_hash', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
