# Generated by Django 5.2.3 on 2025-06-22 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elections', '0002_initial'),
        ('reports', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditreport',
            name='generated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.adminuser'),
        ),
        migrations.AddField(
            model_name='performancereport',
            name='generated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.adminuser'),
        ),
        migrations.AddField(
            model_name='reportschedule',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.adminuser'),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.adminuser'),
        ),
        migrations.AddField(
            model_name='votingreport',
            name='constituency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.constituency'),
        ),
        migrations.AddField(
            model_name='votingreport',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='elections.election'),
        ),
        migrations.AddField(
            model_name='votingreport',
            name='generated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.adminuser'),
        ),
        migrations.AddIndex(
            model_name='votingreport',
            index=models.Index(fields=['election', 'report_type'], name='reports_vot_electio_fa65d9_idx'),
        ),
        migrations.AddIndex(
            model_name='votingreport',
            index=models.Index(fields=['generated_at'], name='reports_vot_generat_5e14f0_idx'),
        ),
    ]
