# Generated by Django 5.2.3 on 2025-06-23 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_initial'),
        ('reports', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditreport',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='performancereport',
            name='election',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='elections.election'),
        ),
        migrations.AddField(
            model_name='reportschedule',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.adminuser'),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.adminuser'),
        ),
        migrations.AddField(
            model_name='voterreceipt',
            name='constituency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.constituency'),
        ),
        migrations.AddField(
            model_name='voterreceipt',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='elections.election'),
        ),
        migrations.AddField(
            model_name='votingreport',
            name='constituency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.constituency'),
        ),
        migrations.AddField(
            model_name='votingreport',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='elections.election'),
        ),
        migrations.AddField(
            model_name='votingreport',
            name='generated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.adminuser'),
        ),
        migrations.AddIndex(
            model_name='auditreport',
            index=models.Index(fields=['action'], name='reports_aud_action_93f26b_idx'),
        ),
        migrations.AddIndex(
            model_name='auditreport',
            index=models.Index(fields=['timestamp'], name='reports_aud_timesta_e2d856_idx'),
        ),
        migrations.AddIndex(
            model_name='auditreport',
            index=models.Index(fields=['user'], name='reports_aud_user_id_ea60e5_idx'),
        ),
        migrations.AddIndex(
            model_name='performancereport',
            index=models.Index(fields=['metric'], name='reports_per_metric_f5c8d8_idx'),
        ),
        migrations.AddIndex(
            model_name='performancereport',
            index=models.Index(fields=['timestamp'], name='reports_per_timesta_39bf89_idx'),
        ),
        migrations.AddIndex(
            model_name='voterreceipt',
            index=models.Index(fields=['voter_hash'], name='reports_vot_voter_h_fc4502_idx'),
        ),
        migrations.AddIndex(
            model_name='voterreceipt',
            index=models.Index(fields=['verification_code'], name='reports_vot_verific_a20477_idx'),
        ),
        migrations.AddIndex(
            model_name='votingreport',
            index=models.Index(fields=['election', 'report_type'], name='reports_vot_electio_fa65d9_idx'),
        ),
        migrations.AddIndex(
            model_name='votingreport',
            index=models.Index(fields=['generated_at'], name='reports_vot_generat_5e14f0_idx'),
        ),
    ]
